BEGIN
DECLARE CURSOR DESCR
IS SELECT * FROM TARIFACOD N ORDER BY N.CODIGO;
BEGIN
   FOR RTARIFACOD IN DESCR LOOP
      BEGIN
      UPDATE NVOTARIFARIO T
      SET  T.DESCRIPCION = RTARIFACOD.DESCRIPCION
      WHERE T.CODIGO = RTARIFACOD.CODIGO AND
            UPPER(T.DESCRIPCION) <> UPPER(RTARIFACOD.DESCRIPCION);
      EXCEPTION
      WHEN OTHERS THEN         
      DBMS_OUTPUT.PUT_LINE('No se pudo actualizar el rubro '||sqlerrm);
      END;      
   END LOOP;
END;
END;
