BEGIN
DECLARE
CURSOR PROC IS
SELECT T.CODIGO_ITEM,T.TIPO
FROM TARIFARIOS T
WHERE T.CODIGO_ITEM IS NOT NULL ORDER BY 1;
BEGIN
   FOR RPROC IN PROC LOOP
   BEGIN
      UPDATE PROCEDIMIENTOS_HOSPITALARIOS  P
      SET P.TRF_TIPO = RPROC.TIPO
      WHERE P.CODIGO_TARIFARIO = RPROC.CODIGO_ITEM;
   EXCEPTION
   WHEN OTHERS THEN
      NULL;   
   END;   
   END LOOP;
END;
END;