-- OJOOOO
-- PRIMERO CREAR ESTA TABLA TEMPORAL
-- CREATE TABLE CONVENIOS_EQUIVALENCIAS_TMP AS SELECT * FROM CONVENIOS_EQUIVALENCIAS D WHERE  -- D.CNVTRF_CONVENIO='X';

DECLARE
  CURSOR C_CONVENIOS IS
  SELECT * FROM CONVENIOS_EQUIVALENCIAS C
   WHERE C.CNVTRF_CONVENIO = 'TRFIESS' AND
      (C.CRG_TIPO,C.CRG_CODIGO) IN (SELECT CG.TIPO,CG.CODIGO
                                    FROM CARGOS CG
                                    WHERE NVL(CG.GOBIERNO,'F') = 'F' AND
                                          NVL(CG.IESS,'F') = 'F') 
                                          AND C.CNVTRF_CODIGO<>'9999999999';
CONT NUMBER;
BEGIN
CONT:=0;
  FOR X IN C_CONVENIOS LOOP
    BEGIN
      INSERT INTO CONVENIOS_EQUIVALENCIAS VALUES(X.CRG_CODIGO, X.CRG_TIPO, 'MSPJUN2011', X.CNVTRF_CODIGO, X.TIPO,X.PRIORIDAD_CARGO);
    EXCEPTION WHEN OTHERS THEN  
      INSERT INTO CONVENIOS_EQUIVALENCIAS_TMP VALUES(X.CRG_CODIGO, X.CRG_TIPO, 'MSPJUN2011', X.CNVTRF_CODIGO, X.TIPO,X.PRIORIDAD_CARGO);
    END;  
    CONT:=CONT+1;
  END LOOP;
      DBMS_OUTPUT.PUT_LINE(CONT);
END;  