-- \\Svr\Z\sas\guiones\CAMBIOS SISTEMA CON TARIFARIO\CONVENIOS_EQUIVALENCIAS.sql
--
-- Generated for Oracle 9i on Fri Jun 24  14:50:05 2011 by Server Generator 6.5.96.5.6


SPOOL CONVENIOS_EQUIVALENCIAS.lst

@@CONVENIOS_EQUIVALENCIAS.tab
@@CONVENIOS_EQUIVALENCIAS.ind
@@CONVENIOS_EQUIVALENCIAS.con

SPOOL OFF
