PL/SQL Developer Test script 3.0
8
BEGIN
DECLARE CONVENIO varCHAR2(25) := NULL;
PROMOCION CHAR(2);
BEGIN
   CONVENIO := FCTCONTRF.DEVUELVE_CONVENIO(5137,SYSDATE,PROMOCION);
   DBMS_OUTPUT.put_line('La promocion es '||convenio); 
END;
END;
0
1
PROMOCION
