-- \\Svr\Z\sas\guiones\CAMBIOS SISTEMA CON TARIFARIO\GRUPOS_TARIFARIOS_FINAL.sql
--
-- Generated for Oracle 9i on Fri Jun 17  14:19:55 2011 by Server Generator 6.5.96.5.6


SPOOL GRUPOS_TARIFARIOS_FINAL.lst

@@GRUPOS_TARIFARIOS_FINAL.ind
@@GRUPOS_TARIFARIOS_FINAL.con

SPOOL OFF
