-- \\Svr\Z\sas\guiones\CAMBIOS SISTEMA CON TARIFARIO\MODIFICA_TARIFARIO_INDICES.sql
--
-- Generated for Oracle 9i on Wed Jul 06  13:14:26 2011 by Server Generator 6.5.96.5.6


SPOOL MODIFICA_TARIFARIO_INDICES.lst

@@MODIFICA_TARIFARIO_INDICES.tab
@@MODIFICA_TARIFARIO_INDICES.ind

SPOOL OFF
