-- \\Svr\Z\sas\guiones\CAMBIOS SISTEMA CON TARIFARIO\PROCEDIMIENTOS_HOSPITALARIOS_ADICIONAL.sql
--
-- Generated for Oracle 10g on Mon Jun 06  12:33:35 2011 by Server Generator 6.5.96.5.6


SPOOL PROCEDIMIENTOS_HOSPITALARIOS_ADICIONAL.lst

@@PROCEDIMIENTOS_HOSPITALARIOS_ADICIONAL.tab
@@PROCEDIMIENTOS_HOSPITALARIOS_ADICIONAL.ind
@@PROCEDIMIENTOS_HOSPITALARIOS_ADICIONAL.con
@@PROCEDIMIENTOS_HOSPITALARIOS_ADICIONAL.avt

SPOOL OFF
