-- \\Svr\Z\sas\guiones\CAMBIOS SISTEMA CON TARIFARIO\PROCEDIMIENTOS_REALIZADOS.sql
--
-- Generated for Oracle 9i on Tue Jun 28  09:39:25 2011 by Server Generator 6.5.96.5.6


SPOOL PROCEDIMIENTOS_REALIZADOS.lst

@@PROCEDIMIENTOS_REALIZADOS.tab
@@PROCEDIMIENTOS_REALIZADOS.avt

SPOOL OFF
