-- \\Svr\Z\sas\guiones\CAMBIOS SISTEMA CON TARIFARIO\PROCEDIMIENTOS_HOSPITALARIOS.sql
--
-- Generated for Oracle 9i on Sun Jun 05  11:42:23 2011 by Server Generator 6.5.96.5.6


SPOOL PROCEDIMIENTOS_HOSPITALARIOS.lst

@@PROCEDIMIENTOS_HOSPITALARIOS.tab
@@PROCEDIMIENTOS_HOSPITALARIOS.avt

SPOOL OFF
