CREATE TABLE CUENTAS_GNR_RECATEGORIZADAS AS SELECT DISTINCT C.PCN_NUMERO_HC FROM CUENTAS C
WHERE C.PCN_NUMERO_HC IN (SELECT CC.PCN_NUMERO_HC_MIGRADO FROM CUENTAS CC
                          WHERE  CC.PCN_NUMERO_HC_MIGRADO IS NOT NULL AND CC.PCN_NUMERO_HC =83405)  AND
C.ESTADO = 'FCT' AND C.RECATEGORIZADA = 'V' AND C.PLA_NUMERO_PLANILLA IS NULL  AND C.PRM_CODIGO <> '22'                
ORDER BY C.FECHA DESC

BEGIN
DECLARE CURSOR PCN IS 
SELECT DISTINCT C.PCN_NUMERO_HC FROM CUENTAS C
WHERE C.PCN_NUMERO_HC IN (SELECT CC.PCN_NUMERO_HC_MIGRADO FROM CUENTAS CC
                          WHERE  CC.PCN_NUMERO_HC_MIGRADO IS NOT NULL AND CC.PCN_NUMERO_HC =83405)  AND
C.ESTADO = 'PND' AND C.RECATEGORIZADA = 'V' AND C.PLA_NUMERO_PLANILLA IS NULL  AND C.PRM_CODIGO <> '22';               
BEGIN
   FOR RPCN IN PCN LOOP
      IESS.RECATEGORIZAR_PCN_IESS('01/07/2011','31/12/2011',RPCN.PCN_NUMERO_HC);
   END LOOP;
END;
END;

SELECT SUM(CR.CANTIDAD*CR.PORCENTAJE_PROMOCION*CR.VALOR) FROM CUENTAS_GNR_RECATEGORIZADAS CR