BEGIN
DECLARE CURSOR CONVENIO
IS SELECT * FROM TARIFARIO_AGOSTO N ORDER BY N.CODIGO;
CURSOR CONVENIO_ANT
IS SELECT * FROM TARIFARIOS T ORDER BY T.CODIGO_ITEM;
ITEM VARCHAR2(4000);
ITEM2 VARCHAR2(10);
BEGIN
   FOR RCONVENIO IN CONVENIO LOOP
      BEGIN
      SELECT T.CODIGO_ITEM INTO ITEM
      FROM TARIFARIOS T
      WHERE T.CODIGO_ITEM = RCONVENIO.CODIGO AND
            UPPER(T.DESCRIPCION_ITEM) = UPPER(RCONVENIO.DESCRIPCION);
      EXCEPTION
      WHEN NO_DATA_FOUND THEN
         INSERT INTO NVOTARIFARIO_AGOSTO_NO_EXISTE
         VALUES(RCONVENIO.CODIGO,UPPER(RCONVENIO.DESCRIPCION),RCONVENIO.UVR,
                RCONVENIO.NIVELI,RCONVENIO.NIVELII,RCONVENIO.NIVELIII,
                RCONVENIO.UVRHMED,RCONVENIO.UVRANES);
      WHEN OTHERS THEN
         NULL;       
      END;   
   END LOOP;
   FOR RCONVENIO_ANT IN CONVENIO_ANT LOOP
      BEGIN
      SELECT N.CODIGO INTO ITEM2
      FROM NVOTARIFARIO N
      WHERE N.CODIGO = RCONVENIO_ANT.CODIGO_ITEM; 
      EXCEPTION
      WHEN NO_DATA_FOUND THEN
         INSERT INTO TARIFARIOS_JUN2011_NO_EXISTE
         VALUES(RCONVENIO_ANT.CODIGO_ITEM,UPPER(RCONVENIO_ANT.DESCRIPCION_ITEM));
      WHEN OTHERS THEN 
         NULL;   
      END;   
   END LOOP;   
END;
END;
