BEGIN
DECLARE CURSOR CONVENIO
IS SELECT * FROM TARIFARIO_AGOSTO N ORDER BY N.CODIGO;
BEGIN
   FOR RCONVENIO IN CONVENIO LOOP
      BEGIN
      UPDATE TARIFARIOS T
      SET T.UVR_H_MED = TO_NUMBER(REPLACE(RCONVENIO.UVRHMED,',','.')),
          T.UVR =  TO_NUMBER(REPLACE(RCONVENIO.UVR,',','.')),
          T.ANES = TO_NUMBER(REPLACE(RCONVENIO.UVRANES,',','.')),
          T.UVR1 = TO_NUMBER(REPLACE(RCONVENIO.NIVELI,',','.')),
          T.UVR2 = TO_NUMBER(REPLACE(RCONVENIO.NIVELII,',','.')),
          T.UVR3 = TO_NUMBER(REPLACE(RCONVENIO.NIVELIII,',','.'))
          T.DESCRIPCION_ITEM = UPPER(RCONVENIO.DESCRIPCION)
      WHERE T.CODIGO_ITEM = RCONVENIO.CODIGO AND
            UPPER(T.DESCRIPCION_ITEM) = UPPER(RCONVENIO.DESCRIPCION);
      EXCEPTION
      WHEN OTHERS THEN         
      DBMS_OUTPUT.PUT_LINE('No se pudo actualizar el rubro '||sqlerrm);
      END;      
      BEGIN
      UPDATE TARIFARIOS T
      SET T.UVR_H_MED = TO_NUMBER(REPLACE(RCONVENIO.UVRHMED,',','.')),
          T.UVR =  TO_NUMBER(REPLACE(RCONVENIO.UVR,',','.')),
          T.ANES = TO_NUMBER(REPLACE(RCONVENIO.UVRANES,',','.')),
          T.UVR1 = TO_NUMBER(REPLACE(RCONVENIO.NIVELI,',','.')),
          T.UVR2 = TO_NUMBER(REPLACE(RCONVENIO.NIVELII,',','.')),
          T.UVR3 = TO_NUMBER(REPLACE(RCONVENIO.NIVELIII,',','.')),
          T.DESCRIPCION_ITEM = UPPER(RCONVENIO.DESCRIPCION)
      WHERE T.CODIGO_ITEM = RCONVENIO.CODIGO AND
            UPPER(T.DESCRIPCION_ITEM) <> UPPER(RCONVENIO.DESCRIPCION);
      EXCEPTION
      WHEN OTHERS THEN         
      DBMS_OUTPUT.PUT_LINE('No se pudo actualizar el rubro '||sqlerrm);
      END;      
   END LOOP;
END;
END;
