<SELECT * FROM CARGOS
WHERE ESTADO_DE_DISPONIBILIDAD = 'D' AND NVL(GOBIERNO,'F') = 'F' AND NVL(IESS,'F') = 'F'  AND
(TIPO||CODIGO)  NOT IN (SELECT CE.CRG_TIPO||CE.CRG_CODIGO
                                           FROM CONVENIOS_EQUIVALENCIAS CE
                                           WHERE CE.CNVTRF_CONVENIO = 'TRFIESS')  AND
(TIPO,CODIGO) IN (SELECT  C.CRG_TIPO,C.CRG_CODIGO FROM CUENTAS C
                   WHERE C.PRM_CODIGO IN ('75','23') AND C.FECHA > '31/08/2011') ORDER BY  DESCRIPCION