((NVL(:CBCINS.MOSTRAR,'F') = 'F' AND 
((NVL(:CBCINS.TARIFAIO,'SIN TARIFARIO' = 'SIN TARIFARIO') AND
TIPO||CODIGO NOT IN (SELECT C.CRG_TIPO||C.CRG_CODIGO FROM CONVENIOS_EQUIVALENCIAS C)) OR
(NVL(:CBCINS.TARIFAIO,'SIN TARIFARIO' <> 'SIN TARIFARIO') AND
TIPO||CODIGO  IN (SELECT C.CRG_TIPO||C.CRG_CODIGO FROM CONVENIOS_EQUIVALENCIAS C WHERE C.CNVTRF_CONVENIO = :CBCINS.TARIFARIO))))
OR 
(NVL:CBCINS.MOSTRAR = 'V' AND 
((NVL(:CBCINS.TARIFAIO,'SIN TARIFARIO' = 'SIN TARIFARIO') AND
TIPO||CODIGO NOT IN (SELECT C.CRG_TIPO||C.CRG_CODIGO FROM CONVENIOS_EQUIVALENCIAS C)) OR
(NVL(:CBCINS.TARIFAIO,'SIN TARIFARIO' <> 'SIN TARIFARIO') AND
TIPO||CODIGO  IN (SELECT C.CRG_TIPO||C.CRG_CODIGO FROM CONVENIOS_EQUIVALENCIAS C WHERE C.CNVTRF_CONVENIO = :CBCINS.TARIFARIO))))
)

