UPDATE CARGOS C
SET C.COSTO = ROUND(NVL((SELECT T.UVR*T.PRC FROM TARIFARIOS  T
               WHERE T.CONVENIO = 'TRFIESS' AND
                     T.CODIGO_ITEM = C.CODIGO_IESS),0),2)
WHERE C.IESS = 'V' AND
      NVL(C.ANESTESIA_IESS,'F') = 'F'
      
UPDATE CARGOS C
SET C.COSTO = ROUND(NVL((SELECT T.ANES*T.PRC_ANES FROM TARIFARIOS  T
               WHERE T.CONVENIO = 'TRFIESS' AND
                     T.CODIGO_ITEM = C.CODIGO_IESS),0),2)
WHERE C.IESS = 'V' AND
      NVL(C.ANESTESIA_IESS,'F') = 'V'
                    
                     
SELECT * FROM CARGOS C
WHERE C.IESS = 'V' ORDER BY C.DESCRIPCION


SELECT *  FROM CARGOS C
WHERE C.COSTO = 0 AND C.IESS = 'V'


SELECT * FROM CARGOS C
WHERE C.IESS = 'V'

SELECT DISTINCT PRC_ANES FROM TARIFARIOS T WHERE T.CONVENIO = 'TRFIESS'

SELECT COUNT(*) FROM CARGOS C
WHERE NVL(C.ANESTESIA_IESS,'F') = 'V'
AND C.IESS <> 'V'



---------------------------- MSPJUN2011

UPDATE CARGOS C
SET C.COSTO = NVL((SELECT T.UVR*T.PRC FROM CONVENIOS_TARIFARIOS T
               WHERE T.CONVENIO = 'MSPJUN2011' AND
                     T.CODIGO = C.CODIGO_IESS),-1)
WHERE C.GOBIERNO = 'V'
                    
                     
SELECT * FROM CARGOS C
WHERE C.GOBIERNO = 'V' ORDER BY C.DESCRIPCION


SELECT *  FROM CARGOS C
WHERE C.COSTO = 0 AND C.IESS = 'V'
