UPDATE TARIFARIOS T
SET T.PRC = 1.961,
    T.PRC2 = 1.627
WHERE T.CONVENIO = 'TRFIESS' AND
      T.PRC = 1.96
/

UPDATE TARIFARIOS T
SET T.PRC = 17.754,
    T.PRC2 = 14.791
WHERE T.CONVENIO = 'TRFIESS' AND
      T.PRC = 17.75
/
      
UPDATE TARIFARIOS T     ----OJO  para portoviejo y Machala se debe cambiar el precio de prc_anes y
SET T.PRC_ANES = 17.754  -- dejarlo en $14.791
WHERE T.CONVENIO = 'TRFIESS' AND
      T.PRC_ANES = 17.75   
/
      
UPDATE TARIFARIOS T
SET T.PRC = 2,
    T.PRC2 = 1.66
WHERE T.CONVENIO = 'TRFIESS' AND
      T.PRC = 2
/

UPDATE TARIFARIOS T
SET T.PRC = 23.365,
    T.PRC2 = 19.558
WHERE T.CONVENIO = 'TRFIESS' AND
      T.PRC = 23.4 
/

UPDATE TARIFARIOS T
SET T.PRC = 2.91,
    T.PRC2 = 2.43
WHERE T.CONVENIO = 'TRFIESS' AND
      T.PRC = 2.91
/

UPDATE TARIFARIOS T
SET T.PRC = 1.064,
    T.PRC2 = 0.887
WHERE T.CONVENIO = 'TRFIESS' AND
      T.PRC = 1.1
/      
      