-- \\Svr\Z\sas\guiones\CAMBIOS SISTEMA CON TARIFARIO\ICSC\CONVENIOS_FIN.grt
--
-- Generated for Oracle 9i on Wed Aug 03  09:28:47 2011 by Server Generator 6.5.96.5.6
 

PROMPT Granting Object Privileges
GRANT SELECT ON CONVENIOS TO GENERAL
/

GRANT DELETE, INSERT, SELECT, UPDATE ON CONVENIOS TO SIS_ADMIN
/

GRANT DELETE, INSERT, SELECT, UPDATE ON CONVENIOS TO ADMINISTRADOR_MAESTROS
/

GRANT DELETE, INSERT, SELECT, UPDATE ON CONVENIOS TO ADMINISTRADOR_PROMOCIONES
/


