-- \\Svr\Z\sas\guiones\CAMBIOS SISTEMA CON TARIFARIO\ICSC\CONVENIOS_EQUIVALENCIAS_MOD.sql
--
-- Generated for Oracle 9i on Wed Nov 16  11:27:56 2011 by Server Generator 6.5.96.5.6


SPOOL CONVENIOS_EQUIVALENCIAS_MOD.lst

@@CONVENIOS_EQUIVALENCIAS_MOD.drp
@@CONVENIOS_EQUIVALENCIAS_MOD.tab
@@CONVENIOS_EQUIVALENCIAS_MOD.ind
@@CONVENIOS_EQUIVALENCIAS_MOD.avt

SPOOL OFF
