-- \\Svr\Z\sas\guiones\CAMBIOS SISTEMA CON TARIFARIO\ICSC\CONVENIOS_EQUI_PROMO.sql
--
-- Generated for Oracle 9i on Wed Aug 03  10:03:23 2011 by Server Generator 6.5.96.5.6


SPOOL CONVENIOS_EQUI_PROMO.lst

@@CONVENIOS_EQUI_PROMO.tab
@@CONVENIOS_EQUI_PROMO.ind
@@CONVENIOS_EQUI_PROMO.con
@@CONVENIOS_EQUI_PROMO.trg
@@CONVENIOS_EQUI_PROMO.avt
@@CONVENIOS_EQUI_PROMO.grt

SPOOL OFF
