BEGIN
DECLARE CURSOR CONVENIO
IS SELECT * FROM TARIFARIO_IESS N WHERE N.CODIGO_GRUPO = 'HON' ORDER BY N.CODIGO_ITEM;
BEGIN
   FOR RCONVENIO IN CONVENIO LOOP
      BEGIN
      UPDATE TARIFARIOS T
      SET T.UVR =  TO_NUMBER(REPLACE(RCONVENIO.UVR,',','.')),
          T.ANES = TO_NUMBER(REPLACE(RCONVENIO.UVR_ANES,',','.')),
          T.PRC = TO_NUMBER(REPLACE(RCONVENIO.PRC,',','.')),
          T.PRC_ANES =TO_NUMBER(REPLACE(RCONVENIO.PRC_ANES,',','.')),
          T.DESCRIPCION_ITEM = UPPER(RCONVENIO.DESCRIPCION_ITEM)
      WHERE T.CONVENIO = RCONVENIO.CONVENIO AND
            T.CODIGO_ITEM = RCONVENIO.CODIGO_ITEM;
      EXCEPTION
      WHEN OTHERS THEN         
      DBMS_OUTPUT.PUT_LINE('No se pudo actualizar el rubro '||sqlerrm);
      END;      
   END LOOP;
END;
END;
