INSERT INTO CARGOS C (TIPO,CODIGO,DESCRIPCION,COSTO,IVA,ESTADO_DE_DISPONIBILIDAD,
                      COSTO_MODIFICABLE,DPR_CODIGO,DPR_ARA_CODIGO,EQUIPO_ESPECIAL,
                      AGRCNT_TIPO,TIEMPO,FACTOR,RANGO_MINIMO,RANGO_MAXIMO,
                      OPERADOR,CANTIDAD_MINIMA,EMP_CODIGO,NOMBRE_IESS,CODIGO_IESS,GOBIERNO,IESS)
SELECT 'S','I'||T.CODIGO_ITEM,SUBSTR(T.DESCRIPCION_ITEM,1,120),T.UVR*T.PRC,0,'D',
       'F','I','I','F','2','F',1,0,999999,'N',1,'CSI',SUBSTR(T.DESCRIPCION_ITEM,1,250),
       T.CODIGO_ITEM,'F','V'
FROM TARIFARIOS T       
WHERE T.CONVENIO= 'TRFIESS' AND
      T.TIPO <> 'C'
