-- \\Svr\Z\sas\guiones\CAMBIOS SISTEMA CON TARIFARIO\ICSC\TARIFARIO_INDICES_EXTRAS.sql
--
-- Generated for Oracle 9i on Thu Aug 11  16:57:35 2011 by Server Generator 6.5.96.5.6


SPOOL TARIFARIO_INDICES_EXTRAS.lst

@@TARIFARIO_INDICES_EXTRAS.tab
@@TARIFARIO_INDICES_EXTRAS.ind
@@TARIFARIO_INDICES_EXTRAS.con
@@TARIFARIO_INDICES_EXTRAS.sqs
@@TARIFARIO_INDICES_EXTRAS.trg
@@TARIFARIO_INDICES_EXTRAS.avt

SPOOL OFF
